<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerR4Vz8x5\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerR4Vz8x5/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerR4Vz8x5.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerR4Vz8x5\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerR4Vz8x5\App_KernelDevDebugContainer([
    'container.build_hash' => 'R4Vz8x5',
    'container.build_id' => '2c286336',
    'container.build_time' => 1673444898,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerR4Vz8x5');
