<?php

namespace ContainerR4Vz8x5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_U5c7DvUService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.u5c7DvU' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.u5c7DvU'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
            'product' => ['privates', '.errored..service_locator.u5c7DvU.App\\Entity\\Product', NULL, 'Cannot autowire service ".service_locator.u5c7DvU": it references class "App\\Entity\\Product" but no such service exists.'],
        ], [
            'doctrine' => '?',
            'product' => 'App\\Entity\\Product',
        ]);
    }
}
